apiVersion: v1
kind: Service
metadata:
  name: pod1-service
spec:
  selector:
    app: api-docker-pod1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
